language: crystal
crystal:
  - latest
  - nightly
matrix:
  allow_failures:
    - crystal: nightly
install:
  - shards install
script:
  - crystal spec
  - bin/ameba
  - bin/crystal_coverage spec/workingdays_spec.cr 
